# Generated by Django 5.1.7 on 2025-05-20 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatDeteksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('hasil_diagnosa', models.TextField()),
                ('foto_hasil', models.ImageField(upload_to='hasil_deteksi/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Riwayat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
